# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft.proto',
  package='raftTransport',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nraft.proto\x12\rraftTransport\"c\n\x04Send\x12\x0c\n\x04Type\x18\x01 \x01(\t\x12-\n\tframeInfo\x18\x02 \x01(\x0b\x32\x18.raftTransport.frameRAFTH\x00\x12\x13\n\tvideoName\x18\x03 \x01(\tH\x00\x42\t\n\x07\x63ontent\"W\n\nraftResult\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0c\n\x04\x66orw\x18\x02 \x01(\x0c\x12\x0f\n\x05\x62\x61\x63kw\x18\x03 \x01(\x0cH\x00\x12\x0f\n\x05\x64ummy\x18\x04 \x01(\x05H\x00\x42\t\n\x07\x63ontent\"3\n\tframeRAFT\x12\x0c\n\x04prev\x18\x01 \x01(\x0c\x12\r\n\x05next_\x18\x02 \x01(\x0c\x12\t\n\x01r\x18\x03 \x01(\x05\x32H\n\nraftDetect\x12:\n\x06Upload\x12\x13.raftTransport.Send\x1a\x19.raftTransport.raftResult\"\x00\x62\x06proto3'
)




_SEND = _descriptor.Descriptor(
  name='Send',
  full_name='raftTransport.Send',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='raftTransport.Send.Type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frameInfo', full_name='raftTransport.Send.frameInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='videoName', full_name='raftTransport.Send.videoName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='raftTransport.Send.content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=29,
  serialized_end=128,
)


_RAFTRESULT = _descriptor.Descriptor(
  name='raftResult',
  full_name='raftTransport.raftResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='raftTransport.raftResult.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forw', full_name='raftTransport.raftResult.forw', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='backw', full_name='raftTransport.raftResult.backw', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dummy', full_name='raftTransport.raftResult.dummy', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='raftTransport.raftResult.content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=130,
  serialized_end=217,
)


_FRAMERAFT = _descriptor.Descriptor(
  name='frameRAFT',
  full_name='raftTransport.frameRAFT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prev', full_name='raftTransport.frameRAFT.prev', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_', full_name='raftTransport.frameRAFT.next_', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r', full_name='raftTransport.frameRAFT.r', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=270,
)

_SEND.fields_by_name['frameInfo'].message_type = _FRAMERAFT
_SEND.oneofs_by_name['content'].fields.append(
  _SEND.fields_by_name['frameInfo'])
_SEND.fields_by_name['frameInfo'].containing_oneof = _SEND.oneofs_by_name['content']
_SEND.oneofs_by_name['content'].fields.append(
  _SEND.fields_by_name['videoName'])
_SEND.fields_by_name['videoName'].containing_oneof = _SEND.oneofs_by_name['content']
_RAFTRESULT.oneofs_by_name['content'].fields.append(
  _RAFTRESULT.fields_by_name['backw'])
_RAFTRESULT.fields_by_name['backw'].containing_oneof = _RAFTRESULT.oneofs_by_name['content']
_RAFTRESULT.oneofs_by_name['content'].fields.append(
  _RAFTRESULT.fields_by_name['dummy'])
_RAFTRESULT.fields_by_name['dummy'].containing_oneof = _RAFTRESULT.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['Send'] = _SEND
DESCRIPTOR.message_types_by_name['raftResult'] = _RAFTRESULT
DESCRIPTOR.message_types_by_name['frameRAFT'] = _FRAMERAFT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Send = _reflection.GeneratedProtocolMessageType('Send', (_message.Message,), {
  'DESCRIPTOR' : _SEND,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raftTransport.Send)
  })
_sym_db.RegisterMessage(Send)

raftResult = _reflection.GeneratedProtocolMessageType('raftResult', (_message.Message,), {
  'DESCRIPTOR' : _RAFTRESULT,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raftTransport.raftResult)
  })
_sym_db.RegisterMessage(raftResult)

frameRAFT = _reflection.GeneratedProtocolMessageType('frameRAFT', (_message.Message,), {
  'DESCRIPTOR' : _FRAMERAFT,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raftTransport.frameRAFT)
  })
_sym_db.RegisterMessage(frameRAFT)



_RAFTDETECT = _descriptor.ServiceDescriptor(
  name='raftDetect',
  full_name='raftTransport.raftDetect',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=272,
  serialized_end=344,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upload',
    full_name='raftTransport.raftDetect.Upload',
    index=0,
    containing_service=None,
    input_type=_SEND,
    output_type=_RAFTRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAFTDETECT)

DESCRIPTOR.services_by_name['raftDetect'] = _RAFTDETECT

# @@protoc_insertion_point(module_scope)
