# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import raft_pb2 as raft__pb2


class raftDetectStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.unary_unary(
                '/raftTransport.raftDetect/Upload',
                request_serializer=raft__pb2.Send.SerializeToString,
                response_deserializer=raft__pb2.raftResult.FromString,
                )


class raftDetectServicer(object):
    """The greeting service definition.
    """

    def Upload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_raftDetectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.unary_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=raft__pb2.Send.FromString,
                    response_serializer=raft__pb2.raftResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raftTransport.raftDetect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class raftDetect(object):
    """The greeting service definition.
    """

    @staticmethod
    def Upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raftTransport.raftDetect/Upload',
            raft__pb2.Send.SerializeToString,
            raft__pb2.raftResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
