# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(182, 80)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("siemens icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_pointType = QtWidgets.QComboBox(Dialog)
        self.cb_pointType.setMaximumSize(QtCore.QSize(132, 16777215))
        self.cb_pointType.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cb_pointType.setObjectName("cb_pointType")
        self.verticalLayout.addWidget(self.cb_pointType)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_add = QtWidgets.QPushButton(Dialog)
        self.pb_add.setObjectName("pb_add")
        self.horizontalLayout.addWidget(self.pb_add)
        self.pb_cancel = QtWidgets.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout.addWidget(self.pb_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.pb_cancel.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add"))
        self.pb_add.setText(_translate("Dialog", "Add"))
        self.pb_cancel.setText(_translate("Dialog", "Cancel"))
