# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optFlowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(180, 145)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("siemens icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("siemens icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cb_type = QtWidgets.QComboBox(Dialog)
        self.cb_type.setObjectName("cb_type")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.gridLayout.addWidget(self.cb_type, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.sb_backw = QtWidgets.QSpinBox(Dialog)
        self.sb_backw.setObjectName("sb_backw")
        self.gridLayout.addWidget(self.sb_backw, 1, 1, 1, 1)
        self.sb_forw = QtWidgets.QSpinBox(Dialog)
        self.sb_forw.setObjectName("sb_forw")
        self.gridLayout.addWidget(self.sb_forw, 2, 1, 1, 1)
        self.pb_continue = QtWidgets.QPushButton(Dialog)
        self.pb_continue.setObjectName("pb_continue")
        self.gridLayout.addWidget(self.pb_continue, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OptFlow"))
        self.label.setText(_translate("Dialog", "Model Type"))
        self.cb_type.setItemText(0, _translate("Dialog", "Small"))
        self.cb_type.setItemText(1, _translate("Dialog", "Large"))
        self.label_3.setText(_translate("Dialog", "Range"))
        self.pb_continue.setText(_translate("Dialog", "Continue"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
