# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openpose.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='openpose.proto',
  package='openposeTransport',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eopenpose.proto\x12\x11openposeTransport\"Q\n\x04Send\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0b\n\x03img\x18\x02 \x01(\x0c\x12\t\n\x01h\x18\x03 \x01(\x05\x12\t\n\x01w\x18\x04 \x01(\x05\x12\t\n\x01\x63\x18\x05 \x01(\x05\x12\t\n\x01r\x18\x06 \x01(\x05\" \n\x0eOpenposeResult\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x32X\n\x0eOpenposeDetect\x12\x46\n\x06Upload\x12\x17.openposeTransport.Send\x1a!.openposeTransport.OpenposeResult\"\x00\x62\x06proto3'
)




_SEND = _descriptor.Descriptor(
  name='Send',
  full_name='openposeTransport.Send',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='openposeTransport.Send.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='img', full_name='openposeTransport.Send.img', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='h', full_name='openposeTransport.Send.h', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w', full_name='openposeTransport.Send.w', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c', full_name='openposeTransport.Send.c', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r', full_name='openposeTransport.Send.r', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=118,
)


_OPENPOSERESULT = _descriptor.Descriptor(
  name='OpenposeResult',
  full_name='openposeTransport.OpenposeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='openposeTransport.OpenposeResult.result', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['Send'] = _SEND
DESCRIPTOR.message_types_by_name['OpenposeResult'] = _OPENPOSERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Send = _reflection.GeneratedProtocolMessageType('Send', (_message.Message,), {
  'DESCRIPTOR' : _SEND,
  '__module__' : 'openpose_pb2'
  # @@protoc_insertion_point(class_scope:openposeTransport.Send)
  })
_sym_db.RegisterMessage(Send)

OpenposeResult = _reflection.GeneratedProtocolMessageType('OpenposeResult', (_message.Message,), {
  'DESCRIPTOR' : _OPENPOSERESULT,
  '__module__' : 'openpose_pb2'
  # @@protoc_insertion_point(class_scope:openposeTransport.OpenposeResult)
  })
_sym_db.RegisterMessage(OpenposeResult)



_OPENPOSEDETECT = _descriptor.ServiceDescriptor(
  name='OpenposeDetect',
  full_name='openposeTransport.OpenposeDetect',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=154,
  serialized_end=242,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upload',
    full_name='openposeTransport.OpenposeDetect.Upload',
    index=0,
    containing_service=None,
    input_type=_SEND,
    output_type=_OPENPOSERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPENPOSEDETECT)

DESCRIPTOR.services_by_name['OpenposeDetect'] = _OPENPOSEDETECT

# @@protoc_insertion_point(module_scope)
